### ISSUE TITLE
Does this still work

### ISSUE THREAD

**Issue by Vyil** [analytics-debugger/ga4mp#11]
We are trying to get this working into our own backend, but it seems the solution is made for browser based applications?
(We get issues like "navigator is not defined", when trying to run locally with some testdata).
Also the uip "can be overwritten", but we don't see any of this working, do you send the uip parameter in the body/header/params?

**Comment by Vyil** [comment]
Alright, and what about the UIP parameter for example. How does the application overwrite this?

**Comment by thyngster** [comment]
Just pass it within the tracker initalization:

const ga4track = ga4mp(["G-THYNGSTER"], {  
  user_id: undefined,
  non_personalized_ads: true,
  user_ip_address: '127.0.0.1',
  debug: true
});

**Comment by Vyil** [comment]
Ok we're still not sure how this would technically work.

We see the solution does a GET request to "https://google-analytics.com/g/collect", but the GA4 measurement protocol requires a POST request to : "https://google-analytics.com/mp/collect?". Also we see user_ip_address variable gets set to uip variable towards google analytics, when we manualy try to send this we don't get to see IP/location because it get's ignored.

Could you clarify how this could work?

**Comment by thyngster** [comment]
This issue should had been fixed on the version 0.0.4
