### ISSUE TITLE
Any plans to add support for file:// protocols?

### ISSUE THREAD

**Issue by henrychoi7** [analytics-debugger/ga4mp#13]
Hi, I'm currently working on how to implement GA4 tracking with `file://` protocols for Electron frameworks(based on TypeScript). Do you have any plans or ideas for that specific use case in this library?

Since Google's Measurement Protocol for GA4 is not ready for use in Electron, I couldn't help myself but had to find a solution to integrate it without using UA anymore. But after a few experiments, it didn't go so well.

**Comment by thyngster** [comment]
This should work since there's no protocol checking at all ( no need since it doesn't include a store mechanism ) . Porting the library to TS is in progress, but I don't really know TS at all, so I'm delaying that giving priority to other projects.

What's the issues you're having?

**Comment by henrychoi7** [comment]
I also tried to use other TS libraries (related to GA4), but the real-time data I sent to GA would not appear in the dashboard. If you're giving priority to other projects then it's okay with me. I'll find a way to implement the GA4 in Electron based on TS. The main issue with this library was the TS support.

Thank you for your reply!

**Comment by thyngster** [comment]
@henrychoi7 it's not about priority it's about working on what pays the bills ...

**Comment by henrychoi7** [comment]
Yes, I understand. I apologize if my sentences were unclear.
