### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by RodriSanchez1** [analytics-debugger/ga4mp#16]
Hi! Thanks @thyngster  for your work. Im working on a React app that is wrapped with Cordova to build an Electron app. The project its  [Cboard](https://github.com/cboard-org/cboard)  and the [Cordova Cboard](https://github.com/cboard-org/ccboard) if you want to check it out . 
We want to set up analytics on the Electron app.  I tested your library. On web is working perfecltly but on the Electron app im facing this issue: 

![image](https://github.com/analytics-debugger/ga4mp/assets/80465873/5dbe37a7-cee9-4e77-ae9b-f24119d6ec8d)

I think the problem is in this [line](https://github.com/analytics-debugger/ga4mp/blob/154ad18b39f43fd53e80ca2cbe1985e5658e3b22/src/modules/clientHints.js#L27). The User Agent Data on Electron is: 
`NavigatorUAData : {
    "brands": [],
    "mobile": false,
    "platform": ""
}` 

And 
![image](https://github.com/analytics-debugger/ga4mp/assets/80465873/88b37b08-4cf6-4f1f-b6fd-0aa42664e313)

On the retrived object, doesnt have  `fullVersionList` prop
One solution can be add a comprobation before `(Object.values(d.fullVersionList) || ....)`  something like `(d.fullVersionList && Object.values(d.fullVersionList) || ....)`

**Comment by thyngster** [comment]
yep, some browsers may not have full support for the client hints and the checks are not properly done on the code. I'm reviewing this.
