### ISSUE TITLE
How to change location in GA using the user_ip_address parameter?

### ISSUE THREAD

**Issue by donherick** [analytics-debugger/ga4mp#19]
I am using the `user_ip_address` parameter but the location in GA is not changed.
How can I use the `user_ip_address` to change the location in GA?

**Comment by thyngster** [comment]
D'oh you're right there's a typo on my code. Will fix it today. It will work on next release...
![image](https://github.com/analytics-debugger/ga4mp/assets/1494564/4e5c05fb-951e-4a51-8aaa-6c4735f300e7)

**Comment by thyngster** [comment]
@donherick this has been addresed on the last release.

**Comment by donherick** [comment]
It worked perfectly.

Thank you.
